### ISSUE TITLE
Output doesn't cleanup on exit

### ISSUE THREAD

**Issue by Kwimbee** [vanous/trainer#1]
**Running Win7 Pro 64 bits + WTX**

When exiting program with q key, my WTX is still transmitting (TX LED blinking).
I'm gonna analyse the output signal when I can to see what's on the output.

After that, using another program that uses the WTX works normally and the led turns off (WTX serial port doesn't stay open blocking antoher program that could try to access it)
I've had issues in the past when a serial port stays locked open, WTX would not be detected by the program and unplugging/replugging (hard reset of the COM port) would fix stuff. This is not the case here.

Is the cleanup function ok ?

**Comment by vanous** [comment]
Hi,
github never notified me about this , i just found it today by accident, sorry, will look into it  when time permits.

**Comment by Kwimbee** [comment]
No problem, since it's not really altering functionnality of the trainer or other software ran after an upload that's not really a big issue.

Btw bug noticed on Win7.

**Comment by vanous** [comment]
Hi Vincent,

OK, try this, should be fixing it.
cheers
P.

[trainer_linux.gz](https://github.com/vanous/trainer/files/900671/trainer_linux.gz)
[trainer_w32.zip](https://github.com/vanous/trainer/files/900672/trainer_w32.zip)
[trainer_w64.zip](https://github.com/vanous/trainer/files/900673/trainer_w64.zip)

**Comment by Kwimbee** [comment]
I'm gonna try this in the office tomorrow, thanks for that !

**Comment by Kwimbee** [comment]
Fixed ! 

Works like a charm

**Comment by vanous** [comment]
Nice, thank you for the test!

Cheers
Petr

**Comment by vanous** [comment]
Looks like trainer will soon not be needed. Finally! 😀

**Comment by Kwimbee** [comment]
That's good news Petr ! I hope to hear more about this soon !

>  good things come to those who wait !
